# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from otel_python_grpc_nested_spans import sleeper_pb2 as otel__python__grpc__nested__spans_dot_sleeper__pb2


class SleeperStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sleep = channel.unary_unary(
                '/github.com.erichulburd.otel_grpc_nested_spans.Sleeper/Sleep',
                request_serializer=otel__python__grpc__nested__spans_dot_sleeper__pb2.SleepRequest.SerializeToString,
                response_deserializer=otel__python__grpc__nested__spans_dot_sleeper__pb2.SleepResponse.FromString,
                )


class SleeperServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Sleep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SleeperServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sleep': grpc.unary_unary_rpc_method_handler(
                    servicer.Sleep,
                    request_deserializer=otel__python__grpc__nested__spans_dot_sleeper__pb2.SleepRequest.FromString,
                    response_serializer=otel__python__grpc__nested__spans_dot_sleeper__pb2.SleepResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'github.com.erichulburd.otel_grpc_nested_spans.Sleeper', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Sleeper(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Sleep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/github.com.erichulburd.otel_grpc_nested_spans.Sleeper/Sleep',
            otel__python__grpc__nested__spans_dot_sleeper__pb2.SleepRequest.SerializeToString,
            otel__python__grpc__nested__spans_dot_sleeper__pb2.SleepResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
